### ISSUE TITLE
Config not available inside directive

### ISSUE THREAD

**Issue by chrney** [summernote/angular-summernote#126]
When doing this,

`	angular
		.module('common')
			.directive('textArea', textAreaFn);

	textFieldFn.$inject = [	];
	textAreaFn.$inject = [ '$compile' ];

	function textAreaFn($compile) {
		return {
			require: "?ngModel",
			scope: { 
				options : '='
			},
			template: "<summernote config='options'>{{options }}{{ label }}</summernote>",
			link: function(scope, element, attrs, ngModel) {
				scope.options = {
					height: 300,
					focus: true,
					toolbar: [
						[ 'edit',
							[ 'undo', 'redo']
						], [ 'headline',
							[ 'style' ]
						],[ 'style',
							[ 'bold', 'italic', 'underline', 'clear' ]
						],[ 'alignment',
							[ 'ul', 'ol', 'paragraph' ]
						],
					]
				};
				scope.label = attrs.label;

				$compile(element.contents())(scope)
			}
		};
	}
`

the options are not taken care of. Running the <summernote config='options'> and having the "controllerScopeVariable".options object defined, works just fine. Just not inside another directive's template.

**Comment by lJakel** [comment]
The problem lies within your directive. Changing the scope after to summernote taking over. Because in your HTML if you do options="{height:300}" or any other config combination it works fine. Angular summernote sees that config option and adds it to SummernoteConfig. Changing the scope in the link function will not work since summernote has already been called. You would need to change the scope and have it applied to the dom prior to angular summernote taking over. Same answers that were on your stack overflow question,

**Comment by chrney** [comment]
Could you show me a proof of concept where the mentioned "options='{ height: 300'}" works for you? It clearly does not for me. However, I could then neither config custom buttons within that directive, could I.

**Comment by lJakel** [comment]
[http://jsfiddle.net/gmxe2hcg/8/](url)
