### ISSUE TITLE
2 summernote editor in IE 11

### ISSUE THREAD

**Issue by infostore** [summernote/angular-summernote#98]
Summernote 0.7.0에서 paragraph 선택시 에디터가 오동작하여 0.7.1 버전으로 변경하였습니다.
0.7.1로 변경한 후에 IE에서 에디터가 2개가 보이고 있습니다.
요소 검사를 했을 때 확인한 내용은 영문 버전과 한글 버전이 같이 나타나는 현상이었습니다.

![image](https://cloud.githubusercontent.com/assets/2704627/12059503/cba94730-af9f-11e5-92ed-7a7345086c09.png)

![image](https://cloud.githubusercontent.com/assets/2704627/12059504/de959aec-af9f-11e5-9bb9-356266fb44d4.png)

summernote 문젠지 angular 문젠지 확인 중에 있지만, 일단 이슈로 올려봅니다.

**Comment by Jeroen06** [comment]
I have the same issue in IE11, I have updated to 0.70 and in Chrome and Edge it is working great but in IE11 it shows 2 Summernote edit boxes.

**Comment by Pyohwan** [comment]
+1

**Comment by emeryowa** [comment]
I also have the same issue.
It appears the issue occurs on summernote v0.7.1 and greater. On summernote v0.7.0 the editor appears normal. When using summernote standalone (jquery version, without angular-summernote) the editor also appears normal.

**Comment by outsideris** [comment]
I pushed a commit for trying to fix it. Sorry for taking a time to check it, because my test environment for IE is not good even if it is a critical issue.
I guess it is a timing issue. Honestly, I didn't found what the problem exactly is, but the workaround works for me in IE 11.
Please check it in your code and leave feedback if you can.

I will release the fixed version if I confirm the issue is fixed enough.
@infostore @Jeroen06 @Pyohwan @emeryowa @virtser

**Comment by Jeroen06** [comment]
The fix works for me in IE11, it does not show an double editor anymore.
But the performance is not very good in IE11, there is noticable lag when typing and I can see the CPU usage rise to 30% while typing. In Chrome there is no lag, and the CPU usage stays way lower (~ 1%).

**Comment by outsideris** [comment]
I released v0.7.1 to fix this issue.
I is just a workaround. I discussed with summernote core team about this issue and [they fixed it](https://github.com/summernote/summernote/pull/1628). 
Summernote v0.7.4 will fix this issue. After that I will remove the workaround.
